apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gu35mwczb-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gu35mwczb-java-quarkus-gitops